theme = "onedark"

[editor]
bufferline = "multiple"
cursorline = true
cursor-shape.insert = "bar"
indent-guides.render = true
indent-guides.character = "▏"
line-number = "relative"
shell = ["fish", "-c"]

[keys.normal]
F5 = [":w", ":config-reload"]
A-j = ["keep_primary_selection", "move_line_down", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection", "move_line_down"]
A-k = ["keep_primary_selection", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection"]
C-r = ":config-reload"
C-s = ":w"

[keys.normal.space]
q = ":quit"

[keys.insert]
C-s = [":w", "normal_mode"]
k = { j = "normal_mode" }
