theme = "onedarkv"

[editor]
auto-pairs = false
bufferline = "multiple"
cursorline = true
end-of-line-diagnostics = "hint"
gutters = ["diff", "line-numbers", "spacer"]
line-number = "relative"
shell = ["bash", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▎" 

[editor.statusline]
left = ["mode", "file-name"]
center = []
right = ["diagnostics", "position", "file-encoding"]

[editor.lsp]
# display-inlay-hints = true

[keys.normal]
C-s = ":write"
C-r = [":w", ":config-reload"]
H = "goto_line_start"
L = "goto_line_end"
J = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
K = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
X = "extend_line_above"
Z = { Z = ":wq" }
esc = ["collapse_selection", "keep_primary_selection"]

[keys.insert]
k = { j = "normal_mode" }
C-c = "normal_mode"
C-h = "move_char_left"
C-l = "move_char_right"
C-s = [":w", "normal_mode"]

[keys.select]
"ç" = "normal_mode"
