theme = "onedark"

[editor]
bufferline = "multiple"
cursorline = true
cursor-shape.insert = "bar"
indent-guides.render = true
indent-guides.character = "▏"
line-number = "relative"
shell = ["fish", "-c"]

[keys.normal]
C-r = ":config-reload"
C-s = ":w"

[keys.normal.space]
q = ":quit"

[keys.insert]
C-s = [":w", "normal_mode"]
k = { j = "normal_mode" }
