theme = "onedark"

[editor]
auto-pairs = false
bufferline = "multiple"
cursorline = true
cursor-shape.insert = "bar"
gutters = ["diff", "line-numbers", "spacer", "spacer"]
indent-guides.render = true
indent-guides.character = "▏"
line-number = "relative"
shell = ["fish", "-c"]

[keys.normal]
A-j = ["keep_primary_selection", "move_line_down", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection", "move_line_down"]
A-k = ["keep_primary_selection", "extend_to_line_bounds", "extend_line_above", "split_selection_on_newline", "select_mode", "goto_line_end_newline", "normal_mode", "rotate_selection_contents_forward", "keep_primary_selection"]
C-j = ["collapse_selection", "keep_primary_selecton"]
C-p = "file_picker"
C-s = ":write"
H = "goto_line_start"
L = "goto_line_end"
J = ["move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down", "move_visual_line_down"]
K = ["move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up", "move_visual_line_up"]
G = "goto_file_end"
X = "extend_line_above"
Z = { Z = ":wq" }
"=" = ":format"
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
q = ":q"
Q = ":qa!"

[keys.normal.space.c]
r = [":w", ":config-reload"]
o = ":config-open"
l = ":o ~/.config/helix/languages.toml"
i = ":indent-style 2"

[keys.insert]
k = { j = "normal_mode" }
C-j = "normal_mode"
C-h = "move_char_left"
C-l = "move_char_right"
C-s = [":w", "normal_mode"]

[keys.select]
C-j = "normal_mode"
