theme = "onedarkv"

[editor]
auto-pairs = false
bufferline = "multiple"
cursorline = true
end-of-line-diagnostics = "hint"
# gutters = ["diff", "line-numbers", "spacer"]
gutters = ["line-numbers", "spacer"]
line-number = "relative"
shell = ["bash", "-c"]

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▎" 

# [editor.whitespace]
# render = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "↲"

[editor.statusline]
left = ["mode", "file-name"]
center = []
right = ["diagnostics", "position", "file-encoding"]

# [editor.lsp]
# display-inlay-hints = true Show tip in code

[keys.normal]
C-s = ":write"
C-r = [":w", ":config-reload"]
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

# [keys.normal.space.u]
# l = ":toggle-option whitespace-render" Works only true or false

[keys.insert]
k = { j = "normal_mode" }
C-c = "normal_mode"
C-h = "move_char_left"
C-l = "move_char_right"
C-s = [":w", "normal_mode"]

[keys.select]
"ç" = "normal_mode"

# References
# https://docs.helix-editor.com/themes.html
