env:
  TERM: xterm-256color

shell:
  program: /usr/bin/fish
  #program: /usr/bin/tmux

window:
  dimensions:
    columns: 100 
    lines: 32
  padding:
    x: 8
    y: 8
  opacity: 1.0

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: IBM Plex Mono Medm
    style: Medium
  bold:
    family: IBM Plex Mono Medm
    style: Medium
  italic:
    family: IBM Plex Mono Medm
    style: Italic Medium
  bold_italic:
    family: IBM Plex Mono Medm
    style: Bold Italic Medium
  size: 10.0
  offset:
    x: 0
    y: 0 
  glyph_offset:
    x: 0
    y: 0

cursor:
  style: block
  unfocused_hollow: true

colors:
  primary:
    background: '#23272e'
    foreground: '#abb2bf'

  normal:
    black:   '#1e222a'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

key_bindings:
  - { key: Return, mods: Control|Shift, action: SpawnNewInstance }
