env:
  TERM: xterm-256color

shell:
  program: /usr/bin/tmux

window:
  dimensions:
    columns: 100 
    lines: 22 
  # padding:
  #   x: 8
  #   y: 8

scrolling:
  history: 10000
  multiplier: 3

background_opacity: 1.0

font:
  normal:
    family: IBM Plex Mono
    style: Medium
  bold:
    family: IBM Plex Mono
    style: Medium
  italic:
    family: IBM Plex Mono
    style: Italic Medium
  bold_italic:
    family: IBM Plex Mono
    style: Bold Italic Medium
  size: 11.0
  offset:
    x: 0
    y: -2 
  glyph_offset:
    x: 0
    y: 0

cursor:
  style: Block
  unfocused_hollow: true

# theme: one dark
# https://github.com/rajasegar/alacritty-themes/blob/master/themes/One-Dark.yml
colors:
  # default colors
  primary:
    background: '#23272e'
    foreground: '#abb2bf'

  # normal colors
  normal:
    black:   '#1e222a'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # bright colors
  bright:
    black:   '#1e222a'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'
