# Built-in
alias c='clear'
alias chx='chmod +x'
alias cls='clear'
alias cp='cp -i'
alias cpv='rsync -ah --info=progress2'
alias e='$EDITOR'
alias md='mkdir -p'
alias mv='mv -i'
alias rd='rmdir'
alias rm='rm -i'
alias so='source'

# Change directories
alias .='cd -'
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias cdbig='cd $HOME/Dev/projects/biglinux'
alias cdc='cd $HOME/Dev/dotfiles/config'
alias cddesi='cd $HOME/Design'
alias cddesk='cd $HOME/Desktop'
alias cdd='cd $HOME/Dev/dotfiles'
alias cddev='cd $HOME/Dev'
alias cddoc='cd $HOME/Documents'
alias cddow='cd $HOME/Downloads'
alias cdf='cd $HOME/Dev/projects/fraseologia'
alias cdgame='cd $HOME/Games'
alias cdmoz='cd $HOME/.mozilla/firefox/ph8r9j57.default-release/chrome'
alias cdmus='cd $HOME/Music'
alias cdp='cd $HOME/Dev/projects'
alias cdpic='cd $HOME/Pictures'
alias cdpkg='cd $HOME/packages'
alias cds='cd $HOME/Dev/shortcuts'
alias cdsof='cd $HOME/Softwares'
alias cdt='cd $HOME/Downloads/temp'
alias cdv='cd $HOME/Dev/projects/vitormelo'
alias cdvid='cd $HOME/Videos'
