#!/usr/bin/env bash

main() {
  local kwinrc=$HOME/.config/kwinrc
  local kdeglobals=$HOME/.config/kdeglobals
  local kdecoration2=org.kde.kdecoration2

  # General
  kwc $kdeglobals $kdedecoration2 ElectricBorderMaximize "false"
  kwc $kdeglobals $kdedecoration2 fixed "Segoe,10,-1,5,63,0,0,0,0,0,Semibold"
  kwc $kdeglobals $kdedecoration2 font "Segoe,10,-1,5,63,0,0,0,0,0,Semibold"
  kwc $kdeglobals $kdedecoration2 menuFont "Segoe,10,-1,5,63,0,0,0,0,0,Semibold"
  kwc $kdeglobals $kdedecoration2 shadeSortColumn "true"
  kwc $kdeglobals $kdedecoration2 smallestReadableFont "Segoe,10,-1,5,63,0,0,0,0,0,Semibold"
  kwc $kdeglobals $kdedecoration2 toolBarFont "Segoe,10,-1,5,63,0,0,0,0,0,Semibold"
  kwc $kdeglobals $kdedecoration2 widgetStyle "Breeze"

  # Icons
  kwc $kdeglobals Icons Theme "Sensual-Breeze-Dark"

  # KDE
  kwc $kdeglobals KDE AnimationDurationFactor "0.125"
  kwc $kdeglobals KDE LookAndFeelPackage "org.kde.breezedark.desktop"
  kwc $kdeglobals KDE ShowDeleteCommand "false"
  kwc $kdeglobals KDE ShowIconsOnPushButtons "false"
  kwc $kdeglobals KDE contrast "4"
  kwc $kdeglobals KDE widgetStyle "Oxygen"

  # Kdecoration2
  kwc $kwinrc $kdecoration2 BorderSize "None"
  kwc $kwinrc $kdecoration2 BorderSizeAuto "false"
  kwc $kwinrc $kdecoration2 ButtonsOnLeft=""
  kwc $kwinrc $kdecoration2 ButtonsOnRight=""
  kwc $kwinrc $kdecoration2 ShowToolTips "false"  
  kwc $kwinrc $kdecoration2 library "org.kde.breeze"
  kwc $kwinrc $kdecoration2 theme "Breeze"

  # Plugins
  kwc $kwinrc Plugins blurEnabled "false"
  kwc $kwinrc Plugins overviewEnabled "false"
  kwc $kwinrc Plugins screenedgeEnabled "false"
  kwc $kwinrc Plugins slideEnabled "false"

  # TabBox
  kwc $kwinrc TabBox LayoutName "thumbnail_grid"

  # Window
  kwc $kwinrc Window ElectricBorderMaximize "false"
  kwc $kwinrc Window ElectricBorderTiling "false"
  kwc $kwinrc Window FocusStealingPreventionLevel "0"
}

# KWriteConfig
kwc() {
  kwriteconfig6 --file $1 --group $2 --key $3 $4
}

main
