theme = "onedarkv"

# Syntaxy
"attribute" = { fg = "yellow" }
"comment" = { fg = "fd", modifiers = ["italic"] }
"constant.builtin" = { fg = "orange" }
"constant.character.escape" = { fg = "orange" }
"constant" = { fg = "orange" }
"constant.numeric" = { fg = "orange" }
"constructor" = { fg = "blue" }
"function.builtin" = { fg = "blue" }
"function" = { fg = "blue" }
"function.macro" = { fg = "purple" }
"keyword.control" = { fg = "purple" }
"keyword.control.import" = { fg = "red" }
"keyword.directive" = { fg = "purple" }
"keyword" = { fg = "purple" }
"keyword.operator" = { fg = "cyan" }
"keyword.storage" = { fg = "purple" }
"label" = { fg = "red" }
"namespace" = { fg = "red" }
"operator" = { fg = "cyan" }
"special" = { fg = "blue" }
"string" = { fg = "green" }
"string.regexp" = { fg = "yellow" }
"tag" = { fg = "red" }
"type" = { fg = "purple" }
"variable.builtin" = { fg = "blue" }
"variable" = { fg = "blue" }
"variable.other.member" = { fg = "red" }
"variable.parameter" = { fg = "fg" }

# Diagnostic
"diagnostic" = { fg = "default", bg = "bd", modifiers = ["italic"] }
"diagnostic.deprecated" = { fg = "red" }
"diagnostic.unnecessary" = { bg = "bd" }
"info" = { fg = "blue" }
"hint" = { fg = "fd" }
"warning" = { fg = "yellow" }
"error" = { fg = "red" }

# Diff
"diff.delta" = { fg = "cyan" }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "yellow" }

# Markup
"markup.heading" = { fg = "purple" }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "orange" }
"markup.italic" = { fg = "purple" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.list" = { fg = "yellow" }
"markup.quote" = { fg = "fg" }
"markup.link.url" = { fg = "fg" }
"markup.link.text" = { fg = "fg" }

# UI

# General
"ui.background" = { bg = "bg" }
"ui.background.separator" = { bg = "bg" }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { bg = "ac" } # Select item

# Bufferline
"ui.bufferline" = { fg = "fd" }
"ui.bufferline.active" = { fg = "fg" }

# Cursor
"ui.cursor" = { fg = "fg", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "yellow" }
"ui.cursor.primary" = { fg = "fg", modifiers = ["reversed"] }

# Debug
"ui.debug" = { fg = "red" }

# Help and popup
"ui.help" = { fg = "fg" }
"ui.popup" = { bg = "bg" }

# Hightlight
"ui.highlight" = { bg = "ac" } # Selct in search
"ui.highlight.frameline" = { bg = "fd" }

# Line number
"ui.linenr" = { fg = "ac" }
"ui.linenr.selected" = { fg = "fg" }

# Menu
"ui.menu" = { fg = "fg", bg = "bg" }
"ui.menu.scroll" = { fg = "ac", bg = "bg" }
"ui.menu.selected" = { fg = "fg", bg = "ac" }

# Picker
"ui.picker.header" = { fg = "fd" }
"ui.picker.header.column" = { fg = "fd" }
"ui.picker.header.column.active" = { fg = "fg" }

# Selction
"ui.selection" = { bg = "ac" }
"ui.selection.primary" = { bg = "ac" }
"ui.cursorline.primary" = { bg = "bl" }

# Statusline
"ui.statusline" = { bg = "bg" }
"ui.statusline.inactive" = { fg = "fd" }

# Virtual
"ui.virtual" = { fg = "fl" }
"ui.virtual.indent-guide" = { fg = "ac" }
"ui.virtual.inlay-hint" = { fg = "fd" }
"ui.virtual.jump-label" = { fg = "red" }
"ui.virtual.ruler" = { bg = "dl" }
"ui.virtual.whitespace" = { fg = "fd" }

# Window
"ui.window" = { fg = "fd" }

[palette]
bd = "#1e2227"
bg = "#23272e"
bl = "#2c313c" # cursorline and sel
fd = "#5c6370" # comment
fg = "#abb2bf"
fl = "#0000ff"
ac = "#3d4556" # selection and accent

red    = "#e06c75"
orange = "#d19a66"
yellow = "#e5c07b"
green  = "#98c379"
cyan   = "#56b6c2"
blue   = "#61afef"
purple = "#c678dd"
