inherits = "onedark"

"markup.link.url" = { fg = "cyan" }
"ui.cursor.match" = { fg = "yellow" }

"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "black" }

"ui.help" = { fg = "white", bg = "black" }
"ui.popup" = { bg = "black" }
"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { fg = "white", bg = "gray" }
"ui.menu.scroll" = { fg = "white", bg = "black" }

[palette]
black = "#23272e"

# References
# https://github.com/helix-editor/helix/tree/master/runtime/themes
