inherits = "onedark"

"comment" = { fg = "gray", modifiers = ["italic"] }
"markup.link.url" = { fg = "cyan" }
"ui.cursor.match" = { fg = "yellow" }
"ui.help" = { fg = "white", bg = "black" }
"ui.linenr" = { fg = "#3d4556" }
"ui.menu" = { fg = "white", bg = "black" }
"ui.menu.selected" = { fg = "white", bg = "gray" }
"ui.menu.scroll" = { fg = "white", bg = "black" }
"ui.popup" = { bg = "black" }
"ui.selection" = { bg = "#3d4556" }
"ui.selection.primary" = { bg = "#3d4556" }
"ui.statusline" = { fg = "white", bg = "black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "black" }
"ui.virtual.indent-guide" = { fg = "#3d4556" }

[palette]
black = "gray"
 
# References
# https://github.com/helix-editor/helix/tree/master/runtime/themes
