# Check interative shell
[[ $- != *i* ]] && return

# Load auto-completion
if ! shopt -oq posix; then
  if [[ -f /usr/share/bash-completion/bash_completion ]]; then
    source /usr/share/bash-completion/bash_completion
  elif [[ -f /etc/bash_completion ]]; then
    source /etc/bash_completion
  fi
fi

# Load config
path=$HOME/.config/bash
if [[ -d "$path" ]]; then
  configs=(opts envs aliases functions pkgs apis)
  for config in "${configs[@]}"; do
    [[ -f "$path/$config" ]] && source "$path/$config"
  done
  [[ $- == *i* ]] && bind -f $HOME/.config/bash/inputs
fi

# vim:ft=bash
