#!/usr/bin/env bash

bspdir=$HOME/.config/bspwm

xset -dpms &
xset s off &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd    > /dev/null || sxhkd -c $bspdir/shortcuts &
pgrep -x numlockx > /dev/null || numlockx
pgrep -x feh      > /dev/null || feh --no-fehbg --bg-fill --recursive --randomize $bspdir/wall/** &
pgrep -x polybar  > /dev/null || polybar bottom -c $bspdir/polybar/config.ini &
pgrep -x dunst    > /dev/null || dunst -config $bspdir/dunst/dunstrc &
# pgrep -x picom > /dev/null || picom --config $bspdir/picom/picom.conf &
pgrep -f /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 > /dev/null || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
