#!/bin/sh

# init
export SXHKD_SHELL="/usr/bin/bash"
xsetroot -cursor_name left_ptr

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 8

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc config focused_border_color "#abb2bf"  
bspc config normal_border_color "#23272e"
bspc config active_border_color "#be5046"
bspc config presel_feedback_color "#98c379"

# rules
bspc rule -a chromium desktop='^2'

# autostart
sxhkd &
feh --no-fehbg --bg-scale ~/Pictures/wallhaven-l3r7yq.jpg &
# picom &
dunst &
# $HOME/.config/polybar/launch.sh --blocks &

