#!/usr/bin/env bash

source $HOME/.config/bspwm/autostart

# Simplify commands
bc="bspc config"
bm="bspc monitor -d"
br="bspc rule -a"

# Add workspaces
$bm 1 2 3 4 5 6 7 8 9

# Config
$bc border_width          1
$bc window_gap            8
$bc split_ratio           0.50
$bc single_monocle        true
$bc borderless_monocle    true
$bc gapless_monocle       true
$bc paddingless_monocle   true

# Theme
$bc focused_border_color  "#3d4556"  
$bc normal_border_color   "#2c313c"
$bc active_border_color   "#abb2bf"
$bc presel_feedback_color "#61afef"

# Rules
$br bitwarden-desktop desktop="^3" focus=on follow=on
$br code              desktop="^2" focus=on follow=on
$br conky             border=off   state=floating 
$br dolphin           desktop="^3" focus=on follow=on
$br firefox           desktop="^1" focus=on follow=on
$br kitty             desktop="^2" focus=on follow=on
$br mpv               desktop="^4" focus=on follow=on state=floating 
$br polybar           layer=above
$br qbittorrent       desktop="^5" focus=on follow=on
$br steam             desktop="^4"
$br thunar            desktop="^3" focus=on follow=on
$br vlc               desktop="^4" focus=on follow=on
$br yad               border=off 
