#!/usr/bin/env bash

source $HOME/.config/bspwm/autostart

# Simplify commands
bc="bspc config"
bm="bspc monitor -d"
br="bspc rule -a"

# Add workspaces
$bm 1 2 3 4 5 6 7 8 9

# Config
$bc border_width          3
$bc window_gap            8
$bc split_ratio           0.50
$bc single_monocle        true
$bc borderless_monocle    true
$bc gapless_monocle       true
$bc paddingless_monocle   true

# Theme
$bc focused_border_color  "#5c6370"  
$bc normal_border_color   "#23272e"
$bc active_border_color   "#be5046"
$bc presel_feedback_color "#98c379"

# Rules
$br firefox desktop="^1" focus=on follow=on
$br code    desktop="^2" focus=on follow=on
$br kitty   desktop="^2" focus=on follow=on
$br dolphin desktop="^3" focus=on follow=on
$br nemo    desktop="^3" focus=on follow=on
$br thunar  desktop="^3" focus=on follow=on
$br mpv     desktop="^4" focus=on follow=on state=floating 
$br vlc     desktop="^4" focus=on follow=on
