#!/usr/bin/env bash

pkgs=(
  breeze-gtk
  bspwm
  conky
  dunst
  feh
  jgmenu
  numlockx
  pavucontrol
  picom
  polkit-gnome
  polybar
  qt5ct
  qt6ct
  sxhkd
  xfce4-power-manager
  yad
)

sudo pacman --noconfirm -S "${pkgs[@]}"
