#!/usr/bin/env bash

pkgs=(
  bspwm
  dunst
  feh
  jgmenu
  lxappearance
  numlockx
  pavucontrol
  picom
  polkit-gnome
  polybar
  qt6ct
  rofi
  sxhkd
  xfce4-power-manager
  xorg-xset
  xorg-xsetroot
  yad
)

if command -v apt &>/dev/null; then
  echo 'Instalando pacotes apt...'
  sudo apt install -y "${pkgs[@]}"
elif command -v pacman &>/dev/null; then
  echo 'Instalando pacotes pacman...'
  sudo pacman --noconfirm -S "${pkgs[@]}"
fi
