require('plugins.treesitter')
require('plugins.mini')
require('plugins.lsp')
require('plugins.snacks')
require('plugins.oil')
vim.cmd.runtime('lua/plugins/tmux-navigator.vim')
-- require('plugins.codeium')
