# Style name or JSON path (default 'auto')
style: 'auto'

# Mouse support (TUI-mode only)
mouse: false

# Use pager to display markdown
pager: false

# Word-wrap at width
width: 80

# Show all files, including hidden and ignored
all: false
